default_elevator_type: kone
kone:
  cached_token:
    access_token: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwczovL2Rldi5rb25lLmNvbS9hcGkvIiwiaWF0IjoxNzU1MjQ3NDYxLCJhdWQiOiJrb25lLWFwaXMiLCJzdWIiOiJjNjU2N2RiNS01MmQyLTQ4N2MtOGE3My0yNzk0ZGE3YzVjODkiLCJzY29wZSI6ImFwcGxpY2F0aW9uL2ludmVudG9yeSBjYWxsdjIvZ3JvdXA6SHhLakdjM2tubmg6MSB0b3BvbG9neS9ncm91cDpIeEtqR2Mza25uaDoxIGNhbGx2Mi9ncm91cDpMMVFpbm50ZEVPZzoxIHRvcG9sb2d5L2dyb3VwOkwxUWlubnRkRU9nOjEgY2FsbHYyL2dyb3VwOmZXbGZIeVBsYWNhOjEgdG9wb2xvZ3kvZ3JvdXA6ZldsZkh5UGxhY2E6MSBjYWxsdjIvZ3JvdXA6NFRGeFdSQ3YyM0Q6MSB0b3BvbG9neS9ncm91cDo0VEZ4V1JDdjIzRDoxIGNhbGx2Mi9ncm91cDpqU3FDWHV3cW1qdzoxIHRvcG9sb2d5L2dyb3VwOmpTcUNYdXdxbWp3OjEiLCJzYW5kYm94Ijp0cnVlLCJleHAiOjE3NTUyNTEwNjEsIm9yZyI6MX0.tvUHZJmVAiU_tO_ZoeSinhyYx61F77gigK7_virrBMJ6PNuh5laJJN3rFDw3xR8MX_DHCN4WGTU19hbgjUEbZQ
    expires_at: '2025-08-15T17:44:21.168999'
    token_type: Bearer
  client_id: c6567db5-52d2-487c-8a73-2794da7c5c89
  client_secret: 0e49374816356ff61eeb4dba3e48b92fb024d230160737646177fe1538075fc0
  token_endpoint: https://dev.kone.com/api/v2/oauth2/token
  ws_endpoint: wss://dev.kone.com/stream-v2
solution_provider:
  company_address: Hong Kong, China
  company_name: IBC-AI CO.
  contact_email: test@ibc-ai.com
  contact_person_name: Test Engineer
  contact_phone: +86-123-4567-8901
  tester: Automated Test System
  version: 0.2.1
