default_elevator_type: kone
kone:
  cached_token:
    access_token: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwczovL2Rldi5rb25lLmNvbS9hcGkvIiwiaWF0IjoxNzU0NTQwNzIwLCJhdWQiOiJrb25lLWFwaXMiLCJzdWIiOiJjNjU2N2RiNS01MmQyLTQ4N2MtOGE3My0yNzk0ZGE3YzVjODkiLCJzY29wZSI6ImFwcGxpY2F0aW9uL2ludmVudG9yeSBjYWxsdjIvZ3JvdXA6SHhLakdjM2tubmg6MSB0b3BvbG9neS9ncm91cDpIeEtqR2Mza25uaDoxIGNhbGx2Mi9ncm91cDpMMVFpbm50ZEVPZzoxIHRvcG9sb2d5L2dyb3VwOkwxUWlubnRkRU9nOjEgY2FsbHYyL2dyb3VwOmZXbGZIeVBsYWNhOjEgdG9wb2xvZ3kvZ3JvdXA6ZldsZkh5UGxhY2E6MSBjYWxsdjIvZ3JvdXA6NFRGeFdSQ3YyM0Q6MSB0b3BvbG9neS9ncm91cDo0VEZ4V1JDdjIzRDoxIGNhbGx2Mi9ncm91cDpqU3FDWHV3cW1qdzoxIHRvcG9sb2d5L2dyb3VwOmpTcUNYdXdxbWp3OjEiLCJzYW5kYm94Ijp0cnVlLCJleHAiOjE3NTQ1NDQzMjAsIm9yZyI6MX0.tQ1OD0vvL9gI5-I47_YlsnUeQMwzf7_85voN3d_krLlGnoOvChWfL8HzHRWM4xSJ1CQYxg3XDi8UQIcgfR4UYg
    expires_at: '2025-08-07T13:25:20.694864'
    token_type: Bearer
  client_id: c6567db5-52d2-487c-8a73-2794da7c5c89
  client_secret: 0e49374816356ff61eeb4dba3e48b92fb024d230160737646177fe1538075fc0
  token_endpoint: https://dev.kone.com/api/v2/oauth2/token
  ws_endpoint: wss://dev.kone.com/stream-v2
