# Virtual Building Configuration - fWlfHyPlaca
# Parsed from KONE virtual building interface

building:
  id: "L1QinntdEOg"
  
elevator_groups:
  group_1:
    lifts:
      - id: "Lift 1 - A"
        type: "passenger"
      - id: "Lift 2 - B" 
        type: "passenger"
      - id: "Lift 3 - C"
        type: "passenger"
      - id: "Lift 4 - D"
        type: "passenger"
      - id: "Lift 5 - E"
        type: "passenger"
      - id: "Lift 6 - F"
        type: "passenger"
      - id: "Lift 7 - G"
        type: "passenger"
      - id: "Lift 8 - H"
        type: "passenger"

floors:
  # Floor mapping from the building interface
  # Format: floor_name: {front_id, rear_id}
  
  deck_1:
    level: 41
    lifts:
      lift_1_a: {front: null, rear: null}
      lift_2_b: {front: 1001020, rear: null}
      lift_3_c: {front: 1001030, rear: null}
      lift_4_d: {front: 1001040, rear: null}
      lift_5_e: {front: 1001050, rear: null}
      lift_6_f: {front: 1001060, rear: null}
      lift_7_g: {front: 1001070, rear: null}
      lift_8_h: {front: 1001080, rear: null}
  
  deck_0:
    level: 40
    lifts:
      lift_1_a: {front: 1001010, rear: null}
      lift_2_b: {front: 1001020, rear: null}
      lift_3_c: {front: 1001030, rear: null}
      lift_4_d: {front: 1001040, rear: null}
      lift_5_e: {front: 1001050, rear: null}
      lift_6_f: {front: 1001060, rear: null}
      lift_7_g: {front: 1001070, rear: null}
      lift_8_h: {front: 1001080, rear: null}

  # Regular floors (F_M format represents floor levels)
  f_39:
    level: 39
    lifts:
      lift_1_a: {front: 39000, rear: 39010}
      lift_2_b: {front: 39000, rear: 39010}
      lift_3_c: {front: 39000, rear: 39010}
      lift_4_d: {front: 39000, rear: 39010}
      lift_5_e: {front: 39000, rear: 39010}
      lift_6_f: {front: 39000, rear: 39010}
      lift_7_g: {front: 39000, rear: 39010}
      lift_8_h: {front: 39000, rear: 39010}

  f_38:
    level: 38
    lifts:
      lift_1_a: {front: 38000, rear: 38010}
      lift_2_b: {front: 38000, rear: 38010}
      lift_3_c: {front: 38000, rear: 38010}
      lift_4_d: {front: 38000, rear: 38010}
      lift_5_e: {front: 38000, rear: 38010}
      lift_6_f: {front: 38000, rear: 38010}
      lift_7_g: {front: 38000, rear: 38010}
      lift_8_h: {front: 38000, rear: 38010}

  f_37:
    level: 37
    lifts:
      lift_1_a: {front: 37000, rear: 37010}
      lift_2_b: {front: 37000, rear: 37010}
      lift_3_c: {front: 37000, rear: 37010}
      lift_4_d: {front: 37000, rear: 37010}
      lift_5_e: {front: 37000, rear: 37010}
      lift_6_f: {front: 37000, rear: 37010}
      lift_7_g: {front: 37000, rear: 37010}
      lift_8_h: {front: 37000, rear: 37010}

  f_36:
    level: 36
    lifts:
      lift_1_a: {front: 36000, rear: 36010}
      lift_2_b: {front: 36000, rear: 36010}
      lift_3_c: {front: 36000, rear: 36010}
      lift_4_d: {front: 36000, rear: 36010}
      lift_5_e: {front: 36000, rear: 36010}
      lift_6_f: {front: 36000, rear: 36010}
      lift_7_g: {front: 36000, rear: 36010}
      lift_8_h: {front: 36000, rear: 36010}

  f_35:
    level: 35
    lifts:
      lift_1_a: {front: 35000, rear: 35010}
      lift_2_b: {front: 35000, rear: 35010}
      lift_3_c: {front: 35000, rear: 35010}
      lift_4_d: {front: 35000, rear: 35010}
      lift_5_e: {front: 35000, rear: 35010}
      lift_6_f: {front: 35000, rear: 35010}
      lift_7_g: {front: 35000, rear: 35010}
      lift_8_h: {front: 35000, rear: 35010}

  f_34:
    level: 34
    lifts:
      lift_1_a: {front: 34000, rear: 34010}
      lift_2_b: {front: 34000, rear: 34010}
      lift_3_c: {front: 34000, rear: 34010}
      lift_4_d: {front: 34000, rear: 34010}
      lift_5_e: {front: 34000, rear: 34010}
      lift_6_f: {front: 34000, rear: 34010}
      lift_7_g: {front: 34000, rear: 34010}
      lift_8_h: {front: 34000, rear: 34010}

  f_33:
    level: 33
    lifts:
      lift_1_a: {front: 33000, rear: 33010}
      lift_2_b: {front: 33000, rear: 33010}
      lift_3_c: {front: 33000, rear: 33010}
      lift_4_d: {front: 33000, rear: 33010}
      lift_5_e: {front: 33000, rear: 33010}
      lift_6_f: {front: 33000, rear: 33010}
      lift_7_g: {front: 33000, rear: 33010}
      lift_8_h: {front: 33000, rear: 33010}

  f_32:
    level: 32
    lifts:
      lift_1_a: {front: 32000, rear: 32010}
      lift_2_b: {front: 32000, rear: 32010}
      lift_3_c: {front: 32000, rear: 32010}
      lift_4_d: {front: 32000, rear: 32010}
      lift_5_e: {front: 32000, rear: 32010}
      lift_6_f: {front: 32000, rear: 32010}
      lift_7_g: {front: 32000, rear: 32010}
      lift_8_h: {front: 32000, rear: 32010}

  f_31:
    level: 31
    lifts:
      lift_1_a: {front: 31000, rear: 31010}
      lift_2_b: {front: 31000, rear: 31010}
      lift_3_c: {front: 31000, rear: 31010}
      lift_4_d: {front: 31000, rear: 31010}
      lift_5_e: {front: 31000, rear: 31010}
      lift_6_f: {front: 31000, rear: 31010}
      lift_7_g: {front: 31000, rear: 31010}
      lift_8_h: {front: 31000, rear: 31010}

  f_30:
    level: 30
    lifts:
      lift_1_a: {front: 30000, rear: 30010}
      lift_2_b: {front: 30000, rear: 30010}
      lift_3_c: {front: 30000, rear: 30010}
      lift_4_d: {front: 30000, rear: 30010}
      lift_5_e: {front: 30000, rear: 30010}
      lift_6_f: {front: 30000, rear: 30010}
      lift_7_g: {front: 30000, rear: 30010}
      lift_8_h: {front: 30000, rear: 30010}

  f_29:
    level: 29
    lifts:
      lift_1_a: {front: 29000, rear: 29010}
      lift_2_b: {front: 29000, rear: 29010}
      lift_3_c: {front: 29000, rear: 29010}
      lift_4_d: {front: 29000, rear: 29010}
      lift_5_e: {front: 29000, rear: 29010}
      lift_6_f: {front: 29000, rear: 29010}
      lift_7_g: {front: 29000, rear: 29010}
      lift_8_h: {front: 29000, rear: 29010}

  f_28:
    level: 28
    lifts:
      lift_1_a: {front: 28000, rear: 28010}
      lift_2_b: {front: 28000, rear: 28010}
      lift_3_c: {front: 28000, rear: 28010}
      lift_4_d: {front: 28000, rear: 28010}
      lift_5_e: {front: 28000, rear: 28010}
      lift_6_f: {front: 28000, rear: 28010}
      lift_7_g: {front: 28000, rear: 28010}
      lift_8_h: {front: 28000, rear: 28010}

  f_27:
    level: 27
    lifts:
      lift_1_a: {front: 27000, rear: 27010}
      lift_2_b: {front: 27000, rear: 27010}
      lift_3_c: {front: 27000, rear: 27010}
      lift_4_d: {front: 27000, rear: 27010}
      lift_5_e: {front: 27000, rear: 27010}
      lift_6_f: {front: 27000, rear: 27010}
      lift_7_g: {front: 27000, rear: 27010}
      lift_8_h: {front: 27000, rear: 27010}

  f_26:
    level: 26
    lifts:
      lift_1_a: {front: 26000, rear: 26010}
      lift_2_b: {front: 26000, rear: 26010}
      lift_3_c: {front: 26000, rear: 26010}
      lift_4_d: {front: 26000, rear: 26010}
      lift_5_e: {front: 26000, rear: 26010}
      lift_6_f: {front: 26000, rear: 26010}
      lift_7_g: {front: 26000, rear: 26010}
      lift_8_h: {front: 26000, rear: 26010}

  f_25:
    level: 25
    lifts:
      lift_1_a: {front: 25000, rear: 25010}
      lift_2_b: {front: 25000, rear: 25010}
      lift_3_c: {front: 25000, rear: 25010}
      lift_4_d: {front: 25000, rear: 25010}
      lift_5_e: {front: 25000, rear: 25010}
      lift_6_f: {front: 25000, rear: 25010}
      lift_7_g: {front: 25000, rear: 25010}
      lift_8_h: {front: 25000, rear: 25010}

  f_24:
    level: 24
    lifts:
      lift_1_a: {front: 24000, rear: 24010}
      lift_2_b: {front: 24000, rear: 24010}
      lift_3_c: {front: 24000, rear: 24010}
      lift_4_d: {front: 24000, rear: 24010}
      lift_5_e: {front: 24000, rear: 24010}
      lift_6_f: {front: 24000, rear: 24010}
      lift_7_g: {front: 24000, rear: 24010}
      lift_8_h: {front: 24000, rear: 24010}

  f_23:
    level: 23
    lifts:
      lift_1_a: {front: 23000, rear: 23010}
      lift_2_b: {front: 23000, rear: 23010}
      lift_3_c: {front: 23000, rear: 23010}
      lift_4_d: {front: 23000, rear: 23010}
      lift_5_e: {front: 23000, rear: 23010}
      lift_6_f: {front: 23000, rear: 23010}
      lift_7_g: {front: 23000, rear: 23010}
      lift_8_h: {front: 23000, rear: 23010}

  f_22:
    level: 22
    lifts:
      lift_1_a: {front: 22000, rear: 22010}
      lift_2_b: {front: 22000, rear: 22010}
      lift_3_c: {front: 22000, rear: 22010}
      lift_4_d: {front: 22000, rear: 22010}
      lift_5_e: {front: 22000, rear: 22010}
      lift_6_f: {front: 22000, rear: 22010}
      lift_7_g: {front: 22000, rear: 22010}
      lift_8_h: {front: 22000, rear: 22010}

  f_21:
    level: 21
    lifts:
      lift_1_a: {front: 21000, rear: 21010}
      lift_2_b: {front: 21000, rear: 21010}
      lift_3_c: {front: 21000, rear: 21010}
      lift_4_d: {front: 21000, rear: 21010}
      lift_5_e: {front: 21000, rear: 21010}
      lift_6_f: {front: 21000, rear: 21010}
      lift_7_g: {front: 21000, rear: 21010}
      lift_8_h: {front: 21000, rear: 21010}

  f_20:
    level: 20
    lifts:
      lift_1_a: {front: 20000, rear: 20010}
      lift_2_b: {front: 20000, rear: 20010}
      lift_3_c: {front: 20000, rear: 20010}
      lift_4_d: {front: 20000, rear: 20010}
      lift_5_e: {front: 20000, rear: 20010}
      lift_6_f: {front: 20000, rear: 20010}
      lift_7_g: {front: 20000, rear: 20010}
      lift_8_h: {front: 20000, rear: 20010}

  f_19:
    level: 19
    lifts:
      lift_1_a: {front: 19000, rear: 19010}
      lift_2_b: {front: 19000, rear: 19010}
      lift_3_c: {front: 19000, rear: 19010}
      lift_4_d: {front: 19000, rear: 19010}
      lift_5_e: {front: 19000, rear: 19010}
      lift_6_f: {front: 19000, rear: 19010}
      lift_7_g: {front: 19000, rear: 19010}
      lift_8_h: {front: 19000, rear: 19010}

  f_18:
    level: 18
    lifts:
      lift_1_a: {front: 18000, rear: 18010}
      lift_2_b: {front: 18000, rear: 18010}
      lift_3_c: {front: 18000, rear: 18010}
      lift_4_d: {front: 18000, rear: 18010}
      lift_5_e: {front: 18000, rear: 18010}
      lift_6_f: {front: 18000, rear: 18010}
      lift_7_g: {front: 18000, rear: 18010}
      lift_8_h: {front: 18000, rear: 18010}

  f_17:
    level: 17
    lifts:
      lift_1_a: {front: 17000, rear: 17010}
      lift_2_b: {front: 17000, rear: 17010}
      lift_3_c: {front: 17000, rear: 17010}
      lift_4_d: {front: 17000, rear: 17010}
      lift_5_e: {front: 17000, rear: 17010}
      lift_6_f: {front: 17000, rear: 17010}
      lift_7_g: {front: 17000, rear: 17010}
      lift_8_h: {front: 17000, rear: 17010}

  f_16:
    level: 16
    lifts:
      lift_1_a: {front: 16000, rear: 16010}
      lift_2_b: {front: 16000, rear: 16010}
      lift_3_c: {front: 16000, rear: 16010}
      lift_4_d: {front: 16000, rear: 16010}
      lift_5_e: {front: 16000, rear: 16010}
      lift_6_f: {front: 16000, rear: 16010}
      lift_7_g: {front: 16000, rear: 16010}
      lift_8_h: {front: 16000, rear: 16010}

  f_15:
    level: 15
    lifts:
      lift_1_a: {front: 15000, rear: 15010}
      lift_2_b: {front: 15000, rear: 15010}
      lift_3_c: {front: 15000, rear: 15010}
      lift_4_d: {front: 15000, rear: 15010}
      lift_5_e: {front: 15000, rear: 15010}
      lift_6_f: {front: 15000, rear: 15010}
      lift_7_g: {front: 15000, rear: 15010}
      lift_8_h: {front: 15000, rear: 15010}

  f_14:
    level: 14
    lifts:
      lift_1_a: {front: 14000, rear: 14010}
      lift_2_b: {front: 14000, rear: 14010}
      lift_3_c: {front: 14000, rear: 14010}
      lift_4_d: {front: 14000, rear: 14010}
      lift_5_e: {front: 14000, rear: 14010}
      lift_6_f: {front: 14000, rear: 14010}
      lift_7_g: {front: 14000, rear: 14010}
      lift_8_h: {front: 14000, rear: 14010}

  f_13:
    level: 13
    lifts:
      lift_1_a: {front: 13000, rear: 13010}
      lift_2_b: {front: 13000, rear: 13010}
      lift_3_c: {front: 13000, rear: 13010}
      lift_4_d: {front: 13000, rear: 13010}
      lift_5_e: {front: 13000, rear: 13010}
      lift_6_f: {front: 13000, rear: 13010}
      lift_7_g: {front: 13000, rear: 13010}
      lift_8_h: {front: 13000, rear: 13010}

  f_12:
    level: 12
    lifts:
      lift_1_a: {front: 12000, rear: 12010}
      lift_2_b: {front: 12000, rear: 12010}
      lift_3_c: {front: 12000, rear: 12010}
      lift_4_d: {front: 12000, rear: 12010}
      lift_5_e: {front: 12000, rear: 12010}
      lift_6_f: {front: 12000, rear: 12010}
      lift_7_g: {front: 12000, rear: 12010}
      lift_8_h: {front: 12000, rear: 12010}

  f_11:
    level: 11
    lifts:
      lift_1_a: {front: 11000, rear: 11010}
      lift_2_b: {front: 11000, rear: 11010}
      lift_3_c: {front: 11000, rear: 11010}
      lift_4_d: {front: 11000, rear: 11010}
      lift_5_e: {front: 11000, rear: 11010}
      lift_6_f: {front: 11000, rear: 11010}
      lift_7_g: {front: 11000, rear: 11010}
      lift_8_h: {front: 11000, rear: 11010}

  f_10:
    level: 10
    lifts:
      lift_1_a: {front: 10000, rear: 10010}
      lift_2_b: {front: 10000, rear: 10010}
      lift_3_c: {front: 10000, rear: 10010}
      lift_4_d: {front: 10000, rear: 10010}
      lift_5_e: {front: 10000, rear: 10010}
      lift_6_f: {front: 10000, rear: 10010}
      lift_7_g: {front: 10000, rear: 10010}
      lift_8_h: {front: 10000, rear: 10010}

  f_9:
    level: 9
    lifts:
      lift_1_a: {front: 9000, rear: 9010}
      lift_2_b: {front: 9000, rear: 9010}
      lift_3_c: {front: 9000, rear: 9010}
      lift_4_d: {front: 9000, rear: 9010}
      lift_5_e: {front: 9000, rear: 9010}
      lift_6_f: {front: 9000, rear: 9010}
      lift_7_g: {front: 9000, rear: 9010}
      lift_8_h: {front: 9000, rear: 9010}

  f_8:
    level: 8
    lifts:
      lift_1_a: {front: 8000, rear: 8010}
      lift_2_b: {front: 8000, rear: 8010}
      lift_3_c: {front: 8000, rear: 8010}
      lift_4_d: {front: 8000, rear: 8010}
      lift_5_e: {front: 8000, rear: 8010}
      lift_6_f: {front: 8000, rear: 8010}
      lift_7_g: {front: 8000, rear: 8010}
      lift_8_h: {front: 8000, rear: 8010}

  f_7:
    level: 7
    lifts:
      lift_1_a: {front: 7000, rear: 7010}
      lift_2_b: {front: 7000, rear: 7010}
      lift_3_c: {front: 7000, rear: 7010}
      lift_4_d: {front: 7000, rear: 7010}
      lift_5_e: {front: 7000, rear: 7010}
      lift_6_f: {front: 7000, rear: 7010}
      lift_7_g: {front: 7000, rear: 7010}
      lift_8_h: {front: 7000, rear: 7010}

  f_6:
    level: 6
    lifts:
      lift_1_a: {front: 6000, rear: 6010}
      lift_2_b: {front: 6000, rear: 6010}
      lift_3_c: {front: 6000, rear: 6010}
      lift_4_d: {front: 6000, rear: 6010}
      lift_5_e: {front: 6000, rear: 6010}
      lift_6_f: {front: 6000, rear: 6010}
      lift_7_g: {front: 6000, rear: 6010}
      lift_8_h: {front: 6000, rear: 6010}

  f_5:
    level: 5
    lifts:
      lift_1_a: {front: 5000, rear: 5010}
      lift_2_b: {front: 5000, rear: 5010}
      lift_3_c: {front: 5000, rear: 5010}
      lift_4_d: {front: 5000, rear: 5010}
      lift_5_e: {front: 5000, rear: 5010}
      lift_6_f: {front: 5000, rear: 5010}
      lift_7_g: {front: 5000, rear: 5010}
      lift_8_h: {front: 5000, rear: 5010}

  f_4:
    level: 4
    lifts:
      lift_1_a: {front: 4000, rear: 4010}
      lift_2_b: {front: 4000, rear: 4010}
      lift_3_c: {front: 4000, rear: 4010}
      lift_4_d: {front: 4000, rear: 4010}
      lift_5_e: {front: 4000, rear: 4010}
      lift_6_f: {front: 4000, rear: 4010}
      lift_7_g: {front: 4000, rear: 4010}
      lift_8_h: {front: 4000, rear: 4010}

  f_3:
    level: 3
    lifts:
      lift_1_a: {front: 3000, rear: 3010}
      lift_2_b: {front: 3000, rear: 3010}
      lift_3_c: {front: 3000, rear: 3010}
      lift_4_d: {front: 3000, rear: 3010}
      lift_5_e: {front: 3000, rear: 3010}
      lift_6_f: {front: 3000, rear: 3010}
      lift_7_g: {front: 3000, rear: 3010}
      lift_8_h: {front: 3000, rear: 3010}

  f_2:
    level: 2
    lifts:
      lift_1_a: {front: 2000, rear: 2010}
      lift_2_b: {front: 2000, rear: 2010}
      lift_3_c: {front: 2000, rear: 2010}
      lift_4_d: {front: 2000, rear: 2010}
      lift_5_e: {front: 2000, rear: 2010}
      lift_6_f: {front: 2000, rear: 2010}
      lift_7_g: {front: 2000, rear: 2010}
      lift_8_h: {front: 2000, rear: 2010}

  f_1:
    level: 1
    lifts:
      lift_1_a: {front: 1000, rear: 1010}
      lift_2_b: {front: 1000, rear: 1010}
      lift_3_c: {front: 1000, rear: 1010}
      lift_4_d: {front: 1000, rear: 1010}
      lift_5_e: {front: 1000, rear: 1010}
      lift_6_f: {front: 1000, rear: 1010}
      lift_7_g: {front: 1000, rear: 1010}
      lift_8_h: {front: 1000, rear: 1010}

# Special notations from the interface
special_floors:
  - "1, 2, 3"  # Bottom annotation in the interface

# Floor ID pattern explanation:
# - Regular floors: {floor_number}000 (front), {floor_number}010 (rear)
# - Deck floors: 100{lift_number}{floor_number}0
# - All lifts serve floors 1-39
# - Deck 0 and Deck 1 have special ID patterns
# - Lift 1-A appears to have limited access to top floors (deck levels)
